version: '3'
services:
  kibana:
        image: kibana:latest
        container_name: es-logger-kibana
        ports:
            - 5601:5601
        depends_on:
            - elasticsearch
  elasticsearch:
    image: elasticsearch:latest
    container_name: es-logger
    ports:
      - "9201:9200"
      - "9301:9300"